[global]
dsn = "root:@tcp(172.17.0.1:4000)/"
database = "test"
thread = 4
action = 10

[graph]
begin = 20
commit = 20
rollback = 20
select = 30
select-for-update = 30
insert = 50
update = 50
delete = 50

[depend]
ww = 10
wr = 10
rw = 10
